### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by nuclight** [zhenyolka/DPITunnel-cli#1]
It is absolutely not clear how to use or if it is even worth to try building.

**Comment by zhenyolka** [comment]
@nuclight Hi! I fully understand you. The program is in beta or even alpha. I need to rework autoconfig and counting ttl value. After that I'll add good readme and CI binaries building. Also there are elections in Russia and I need to somehow bypass blocks of DoH services, that will be blocked soon.

Короче, скоро все сделаю.

**Comment by Jrchintu** [comment]
> It is absolutely not clear how to use or if it is even worth to try building.

Since this project is currently under heavy development as stated by @zhenyolka. Still you can compile and test this.
Follow this steps:
1. Clone the repo
```
git clone --depth=1 -b master --single-branch https://github.com/zhenyolka/DPITunnel
```
2. Install cmake and make for linux
```
sudo pacman -Syu cmake make
```
3. use cmake
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
```
4. Finally start build
```
make && make install
```
5. You will get a binary in same folder

- Note: currently many things maybe broken, give bug reports for such.

**Comment by Jrchintu** [comment]
Also about the usage of this final binary:
1. You can use automatic config with
```
./DPITunnel-cli-exec ----auto
```
2. Above command will guide you and you wil get a possible working confing to bypass censorship at your place/network e.g:
```
sudo ./DPITunnel-cli-exec -use-doh -doh-server https://dns.google/dns-query -split-at-sni -ca-bundle-path ./ca.bundle -desync-attacks split -port 1234 -daemon
```
3. You need ca.bundle [Can get from Mozilla website] or can use mk-ca-bundle [Possible present in curl]
4. finally after starting daemon you got in 2nd step you can launch any browser with proxy e.g for chromium:
```
/usr/bin/chromium --proxy-server="http://0.0.0.0:1234"
```
PS: please report if you'r able to use it and if found any bug. @zhenyolka if something wrong please try to correct me.

**Comment by zhenyolka** [comment]
@Jrchintu 0.0.0.0 is wrong IP, you should use 127.0.0.1

**Comment by Jrchintu** [comment]
> 127.0.0.1

Thanks for suggestion :)

**Comment by zhenyolka** [comment]
@nuclight I'll close it as it fixed
